version: '3'

services:
  react:
    build: client
    ports:
      - "3000:3000"

  express:
    build: server
    ports:
      - "5000:5000"
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"