export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPDATE_RECORDS = 'UPDATE_RECORDS';
export const DATE_PICKER_CHANGE = 'DATE_PICKER_CHANGE';
export const SLIDER_CHANGE = 'SLIDER_CHANGE';
export const STOP_RECORDS = 'STOP_RECORDS';